# Generated by Django 2.1.4 on 2018-12-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_demographics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demographics',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
